from . import setting
from . import measurement
from . import so_reject_reason
from . import payment
from . import sale_order
from . import picking
from . import account_move
from . import partner
from . import purchase
